import "../globals.css"
import type { Metadata } from "next"
import { Lexend } from "next/font/google"

const lexend = Lexend({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lexend.className + " flex flex-col items-center"}>
        <div className="w-screen fixed h-screen  bg-gradient-to-br from-10% to-90% from-backdrop to-mirage -z-10">
          {children}
        </div>
      </body>
    </html>
  )
}
