
import "../globals.css"
import type { Metadata } from "next"
import { Lexend } from "next/font/google"
import MainView from "./(components)/MainView"
const lexend = Lexend({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Pong Fury",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={lexend.className}>

				<div className="w-screen fixed h-screen  bg-gradient-to-r from-10% to-80% from-backdrop to-mirage -z-10 "></div>
				<MainView>
					{children}
				</MainView>

			</body>
		</html>
	)
}

