import "../globals.css"
import type { Metadata } from "next"
import { Lexend } from "next/font/google"
import Button from "./Button"
import Cross from "./icons/Cross"

const lexend = Lexend({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={lexend.className + " h-screen flex flex-col items-center"}
      >
        <div className="w-screen h-screen absolute bg-gradient-to-br from-40% bg-gradient-t from-backdrop to-mirage -z-10 "></div>
        <div className="flex justify-end w-full p-5">
          <Cross />
        </div>
        <div className="flex container flex-col md:flex-row justify-center">
          <div className="flex gap-2 w-52 flex-col mx-3">
            <Button title="Profile" selected={true} />
            <Button title="Sign in & Security" />
            <Button title="Game Prefrences" />
          </div>
          <div className="flex-1 max-w-[900px]">{children}</div>
        </div>
      </body>
    </html>
  )
}
